"""add_rosco_submissions_table

Revision ID: 1afd27cb6e09
Revises: 615c337e1862
Create Date: 2026-03-19 11:25:34.746508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1afd27cb6e09'
down_revision: Union[str, Sequence[str], None] = '615c337e1862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rosco_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rosco_id', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rosco_submissions_id'), 'rosco_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_rosco_submissions_rosco_id'), 'rosco_submissions', ['rosco_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rosco_submissions_rosco_id'), table_name='rosco_submissions')
    op.drop_index(op.f('ix_rosco_submissions_id'), table_name='rosco_submissions')
    op.drop_table('rosco_submissions')
    # ### end Alembic commands ###
