"""add monitoring start and end dates

Revision ID: 1f58cad6f90d
Revises: 7bf3b017379f
Create Date: 2026-03-30 10:04:33.053388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f58cad6f90d'
down_revision: Union[str, Sequence[str], None] = '7bf3b017379f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
