"""add_json_summary

Revision ID: 3a4487a52941
Revises: 44a7ffdf4a28
Create Date: 2026-03-19 14:56:14.773654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4487a52941'
down_revision: Union[str, Sequence[str], None] = '44a7ffdf4a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rosco_submissions', sa.Column('qc_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rosco_submissions', 'qc_summary')
    # ### end Alembic commands ###
