"""expand_rosco_logging

Revision ID: 44a7ffdf4a28
Revises: 1afd27cb6e09
Create Date: 2026-03-19 14:19:38.920713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a7ffdf4a28'
down_revision: Union[str, Sequence[str], None] = '1afd27cb6e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rosco_submissions', sa.Column('project_name', sa.String(length=255), nullable=True))
    op.add_column('rosco_submissions', sa.Column('run_duration', sa.Float(), nullable=True))
    op.add_column('rosco_submissions', sa.Column('error_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rosco_submissions', 'error_count')
    op.drop_column('rosco_submissions', 'run_duration')
    op.drop_column('rosco_submissions', 'project_name')
    # ### end Alembic commands ###
