"""add_user_input_fields

Revision ID: 7bf3b017379f
Revises: 3a4487a52941
Create Date: 2026-03-20 14:27:05.386875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf3b017379f'
down_revision: Union[str, Sequence[str], None] = '3a4487a52941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rosco_submissions', sa.Column('manual_rosco_id', sa.String(length=255), nullable=True))
    op.add_column('rosco_submissions', sa.Column('destination_id', sa.String(length=255), nullable=True))
    op.add_column('rosco_submissions', sa.Column('user_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rosco_submissions', 'user_name')
    op.drop_column('rosco_submissions', 'destination_id')
    op.drop_column('rosco_submissions', 'manual_rosco_id')
    # ### end Alembic commands ###
