"""added qc_type to rosco_submissions

Revision ID: a0901350c878
Revises: bdc42937ba6c
Create Date: 2026-06-08 12:21:38.020949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0901350c878'
down_revision: Union[str, Sequence[str], None] = 'bdc42937ba6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rosco_submissions', sa.Column('qc_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rosco_submissions', 'qc_type')
    # ### end Alembic commands ###
